### ISSUE TITLE
Refactor: Merge `ScreenRoutes` and `AppRoute` classes

### ISSUE THREAD

**Issue by aziznal** [remote-gymapp/gymapp-mobile#12]

**Comment by aziznal** [comment]
@muammertkn I don't think we should merge these two files because if we do that then every time we need to access `ScreenRoute` we would also be importing `AppRoute`. it's not a good idea to be accessing things we don't need. Let's close this issue if you agree.

**Comment by ghost** [comment]
@aziznal  Why do we have to access the ScreenRoute? Every variable defined in ScreenRoute will only be defined on AppRoute.  So we do not have to access/import ScreenRoute.

**Comment by aziznal** [comment]
> @aziznal  Why do we have to access the ScreenRoute? Every variable defined in ScreenRoute will only be defined on AppRoute.  So we do not have to access/import ScreenRoute.

Actually, that's incorrect. We will be using `ScreenRoute` all over the application whenever we have to use `Get.to...` methods. That means we need to import `ScreenRoute` in many places, not just `AppRoute`. that's why we made it in the first place.
